[workspace]
members = ["core", "py_binding"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Niem Le"]
description = "TinyML Transfer Learning on Edge â€” no_std Rust AI inference library"
